"""add timesheet reminders and freeze flag

Revision ID: 133a2e0be870
Revises: 4e03accb2e3a
Create Date: 2026-06-12 15:19:54.483456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133a2e0be870'
down_revision: Union[str, Sequence[str], None] = '4e03accb2e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_profiles', sa.Column('timesheet_frozen', sa.Boolean(), nullable=True))
    op.add_column('timesheets', sa.Column('reminder_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timesheets', 'reminder_count')
    op.drop_column('employee_profiles', 'timesheet_frozen')
    # ### end Alembic commands ###
